name: 'Action Helper'
description: 'Helper action'
inputs:
  host:
    description: "SonarQube Server URL"
    required: false
  token:
    description: "Sonarqube token"
    required: false
  githubToken:
    description: "Github token. https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'